name: Backblaze/b2
resources:
    b2_application_key Resource - terraform-provider-b2:
        subCategory: ""
        description: B2 application key resource.
        name: b2_application_key Resource - terraform-provider-b2
        title: b2_application_key Resource - terraform-provider-b2
        argumentDocs: {}
        importStatements: []
    b2_bucket Resource - terraform-provider-b2:
        subCategory: ""
        description: B2 bucket resource.
        name: b2_bucket Resource - terraform-provider-b2
        title: b2_bucket Resource - terraform-provider-b2
        argumentDocs:
            "false": .
        importStatements: []
    b2_bucket_file_version Resource - terraform-provider-b2:
        subCategory: ""
        description: B2 bucket file version resource.
        name: b2_bucket_file_version Resource - terraform-provider-b2
        title: b2_bucket_file_version Resource - terraform-provider-b2
        argumentDocs: {}
        importStatements: []
