apiVersion: b2.backblaze.upbound.io/v1alpha1
kind: Key
metadata:
  name: testkey
spec:
  forProvider:
    keyName: testkey
    bucketIdRef:
      name: testbucket
    capabilities: # Available Capabilities can be found here: https://www.backblaze.com/docs/cloud-storage-application-keys
      - "listFiles"
      - "readFiles"
      - "writeFiles"
      - "listBuckets"
  writeConnectionSecretToRef:
    name: testkey
    namespace: default